#site
site_name: Material for MkDocs
site_description: A Material Design theme for MkDocs
site_author: Martin Donath
site_url: https://squidfunk.github.io/mkdocs-material/

# Repository
repo_name: mudarajeshbabu
repo_url: https://github.com/mudarajeshbabu/
edit_uri: ""
